powerdns:
	@if [ "${r}" = "install" ]; then\
		ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-powerdns.yml --tags='install';\
	elif [ "${r}" = "uninstall" ]; then\
		ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-powerdns.yml --tags='uninstall';\
	else\
		echo "No Actions for PowerDNS Role";\
		exit;\
	fi
